2020.07.12  11:35:30 [main] ERROR by.epam.train2.model.service.impl.TrainSortServiceImpl - by.epam.train2.exception.DaoException: PassengerTrain{destination='Kapushkino', departureTime=2:55, staff amount=7}is already in the list
2020.07.12  11:51:08 [main] ERROR by.epam.train2.model.service.impl.TrainSortServiceImpl - by.epam.train2.exception.DaoException: PassengerTrain{destination='Minsk', departureTime=23:15, staff amount=16}is already in the list
2020.07.12  11:51:08 [main] ERROR by.epam.train2.model.service.impl.TrainSortServiceImpl - by.epam.train2.exception.DaoException: PassengerTrain{destination='Poltava', departureTime=7:46, staff amount=17}is already in the list
2020.07.12  11:51:08 [main] ERROR by.epam.train2.model.service.impl.TrainSortServiceImpl - by.epam.train2.exception.DaoException: PassengerTrain{destination='Lipetevo', departureTime=3:56, staff amount=9}is already in the list
2020.07.12  11:54:16 [main] ERROR by.epam.train2.model.service.impl.TrainSortServiceImpl - by.epam.train2.exception.DaoException: PassengerTrain{destination='Minsk', departureTime=23:15, staff amount=16}is already in the list
2020.07.12  11:54:16 [main] ERROR by.epam.train2.model.service.impl.TrainSortServiceImpl - by.epam.train2.exception.DaoException: PassengerTrain{destination='Poltava', departureTime=7:46, staff amount=17}is already in the list
2020.07.12  11:54:16 [main] ERROR by.epam.train2.model.service.impl.TrainSortServiceImpl - by.epam.train2.exception.DaoException: PassengerTrain{destination='Lipetevo', departureTime=3:56, staff amount=9}is already in the list
2020.07.12  12:06:03 [main] ERROR by.epam.train2.model.service.impl.TrainSortServiceImpl - by.epam.train2.exception.DaoException: PassengerTrain{destination='Lipetevo', departureTime=3:56, staff amount=9}is already in the list
2020.07.12  12:08:16 [main] ERROR by.epam.train2.model.service.impl.TrainSortServiceImpl - by.epam.train2.exception.DaoException: PassengerTrain{destination='Kapushkino', departureTime=2:55, staff amount=7}is already in the list
2020.07.12  12:08:16 [main] ERROR by.epam.train2.model.service.impl.TrainSortServiceImpl - by.epam.train2.exception.DaoException: PassengerTrain{destination='Kapushkino', departureTime=2:55, staff amount=7}is already in the list
2020.07.12  12:08:16 [main] ERROR by.epam.train2.model.service.impl.TrainSortServiceImpl - by.epam.train2.exception.DaoException: PassengerTrain{destination='Moscow', departureTime=12:10, staff amount=14}is already in the list
2020.07.12  12:08:16 [main] ERROR by.epam.train2.model.service.impl.TrainSortServiceImpl - by.epam.train2.exception.DaoException: PassengerTrain{destination='Kapushkino', departureTime=2:55, staff amount=7}is already in the list
2020.07.12  12:08:16 [main] ERROR by.epam.train2.model.service.impl.TrainSortServiceImpl - by.epam.train2.exception.DaoException: PassengerTrain{destination='Kapushkino', departureTime=2:55, staff amount=7}is already in the list
2020.07.12  12:08:16 [main] ERROR by.epam.train2.model.service.impl.TrainSortServiceImpl - by.epam.train2.exception.DaoException: PassengerTrain{destination='Moscow', departureTime=12:10, staff amount=14}is already in the list
